name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dev dependencies
        run: |
          pip install --upgrade pip
          pip install black flake8
      - name: Run Black
        run: black --check .
      - name: Run Flake8
        run: flake8 .

  test-backend:
    runs-on: ubuntu-latest
    needs: lint-python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run Pytest
        run: pytest --maxfail=1 --disable-warnings -q
